$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$htmlDir = Join-Path $root "static-files"
$outputPath = Join-Path (Join-Path $root "src") "Resources.h"

function Get-PreferredFile {
    param (
        [string] $MinifiedFolderFileName,
        [string] $MinifiedFileName,
        [string] $SourceFileName
    )

    $minifiedFolderPath = Join-Path (Join-Path $htmlDir "min") $MinifiedFolderFileName
    if (Test-Path $minifiedFolderPath) {
        return $minifiedFolderPath
    }

    $minifiedPath = Join-Path $htmlDir $MinifiedFileName
    if (Test-Path $minifiedPath) {
        return $minifiedPath
    }

    return Join-Path $htmlDir $SourceFileName
}

function Get-TextResource {
    param (
        [string] $Path
    )

    $utf8 = New-Object System.Text.UTF8Encoding($false, $true)
    return [System.IO.File]::ReadAllText($Path, $utf8)
}

function Get-BinaryResource {
    param (
        [string] $Path
    )

    $bytes = [System.IO.File]::ReadAllBytes($Path)
    $lines = New-Object System.Collections.Generic.List[string]

    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $end = [Math]::Min($i + 15, $bytes.Length - 1)
        $chunk = for ($j = $i; $j -le $end; $j++) {
            "0x{0:X2}" -f $bytes[$j]
        }
        $lines.Add("    " + ($chunk -join ", "))
    }

    return $lines -join ",`r`n"
}

$indexPath = Get-PreferredFile "index.html" "index.min.html" "index.html"
$scriptPath = Get-PreferredFile "index.js" "index.min.js" "index.js"
$stylesPath = Get-PreferredFile "styles.css" "styles.min.css" "styles.css"
$imagePath = Join-Path $htmlDir "corsa.jpg"

$index = Get-TextResource $indexPath
$script = Get-TextResource $scriptPath
$styles = Get-TextResource $stylesPath
$image = Get-BinaryResource $imagePath

$header = @"
// This file is auto-generated by tools/Generate-HtmlResources.ps1.
// Do not edit this file manually.
//
// To update it:
// 1. Edit the source files in static-files/.
// 2. Run the VS Code task: Minify HTML, JS and CSS.
//    Alternatively, run: powershell -NoProfile -ExecutionPolicy Bypass -File tools/Generate-HtmlResources.ps1
//
#pragma once

#include <Arduino.h>

class Resources {
public:
  /**
   * @brief Embedded HTML page served at the web server root.
   */
  inline static const char index[] PROGMEM = R"htmlresource($index)htmlresource";

  /**
   * @brief Embedded JavaScript used by the settings web page.
   */
  inline static const char script[] PROGMEM = R"jsresource($script)jsresource";

  /**
   * @brief Embedded CSS stylesheet used by the settings web page.
   */
  inline static const char styles[] PROGMEM = R"cssresource($styles)cssresource";

  /**
   * @brief Embedded CORSA logo JPEG served by the web server.
   */
  inline static const uint8_t corsa[] PROGMEM = {
$image
  };
};
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputPath, $header, $utf8NoBom)
